name: $(Major).$(Minor).$(Rev:r)
steps:
- task: DotNetCoreCLI@2
  displayName: 'Run Build'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Run Test'
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration Release'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: 'Release'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  displayName: 'Push to Nuget'
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'

