- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '''**/*.csproj'
    arguments: '
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration Release'