steps:
- task: DotNetCoreCLI@2
  displayName: 'Run Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Run Test'
  inputs:
    command: 'test'
    projects: '**/*Test/*.csproj'
    arguments: '--configuration Release'